# Generated by Django 5.0 on 2023-12-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField(choices=[(0, 'В работе'), (1, 'Готов к выдаче')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
