# Generated by Django 5.0 on 2023-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orders_options_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='department',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
